<?php


namespace App\Http\Middleware\Admin;
use App\Http\Middleware\Authenticate as Middleware;
use Closure;

class Authenticate extends Middleware
{

    public function handle($request, Closure $next, ...$guards)
    {
        return parent::handle($request, $next, 'admin'); // TODO: Change the autogenerated stub
    }

    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('admin.auth.show_login_form');
        }
    }

}